## Numpy Attributes

In [1]:
import numpy as np

my_numpy = np.array([
                    [1,2,3,4,5],
                    [6,7,8,9,0]
                    ])
print(my_numpy)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [2]:
my_numpy.ndim

2

In [3]:
my_numpy.shape

(2, 5)

In [4]:
my_numpy.dtype

dtype('int32')

In [5]:
my_numpy.itemsize

4

In [6]:
my_numpy.nbytes

40

## Indexing Arrays

In [7]:
my_numpy[1][2:]

array([8, 9, 0])

## Slicing Arrays

In [9]:
nmp = np.array(range(10))
print(nmp)
nmp[0:6:2]

[0 1 2 3 4 5 6 7 8 9]


array([0, 2, 4])

In [10]:
my_numpy[1:,2:]

array([[8, 9, 0]])

## Reshaping Array

In [11]:
my_numpy.reshape(5,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0]])

## Joining Array

In [12]:
my_numpy = np.array([
                    [1,2,3,4,5],
                    [6,7,8,9,0]
                    ])

nmpy = np.array([
                [1,2,3,1,4], 
                [2,3,5,3,5]
                ])

np.concatenate([my_numpy, nmpy])

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [1, 2, 3, 1, 4],
       [2, 3, 5, 3, 5]])

## Series Pandas

In [15]:
import pandas as pd

x = pd.Series([6,3,4,6])
print(x)

0    6
1    3
2    4
3    6
dtype: int64


In [16]:
x.index = ['a', 'b', 'c', 'd']
print(x)

a    6
b    3
c    4
d    6
dtype: int64


In [17]:
# cara kedua

x = pd.Series([6,3,4,6], index=['a', 'b', 'c', 'd'])
print(x)

a    6
b    3
c    4
d    6
dtype: int64


In [18]:
# check tipe data
print(type(x))

<class 'pandas.core.series.Series'>


## DataFrame Pandas

In [19]:
import pandas as pd

df = pd.DataFrame(
    {'tipe_int': [50, 21], 
     'tipe_string': ['a', 'b']
    })
print(df)

   tipe_int tipe_string
0        50           a
1        21           b


In [20]:
# check tipe data
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [22]:
# membaca dari dari csv
df_from_csv = pd.read_csv('jabar-corona-virus-case.csv')

# membaca data dari excel
df_from_excel = pd.read_excel('jabar-corona-virus-case.xlsx')

In [23]:
df_from_csv.head()

tanggal  kode_prov            nama_prov  kode_kab          nama_kab  \
0  2020-08-01         32  Provinsi Jawa Barat      3208     KAB. KUNINGAN   
1  2020-08-01         32  Provinsi Jawa Barat      3211     KAB. SUMEDANG   
2  2020-08-01         32  Provinsi Jawa Barat      3213       KAB. SUBANG   
3  2020-08-01         32  Provinsi Jawa Barat      3214   KAB. PURWAKARTA   
4  2020-08-01         32  Provinsi Jawa Barat      3278  KOTA TASIKMALAYA   

   closecontact  closecontact_dikarantina  closecontact_discarded  suspect  \
0             0                         0                       0        0   
1             0                         0                       0        0   
2             0                         0                       0        0   
3             0                         0                       0        0   
4             0                         0                       0        0   

   suspect_diisolasi  ...  pertumbuhan_suspect_discarded  \
0                  0  ...                              0   
1                  0  ...                              0   
2                  0  ...                              0   
3                  0  ...                              0   
4                  0  ...                              0   

   pertumbuhan_suspect_diisolasi  pertumbuhan_probable  \
0                              0                     0   
1                              0                     0   
2                              0                     0   
3                              0                     0   
4                              0                     0   

   pertumbuhan_probable_discarded  pertumbuhan_probable_diisolasi  \
0                               0                               0   
1                               0                               0   
2                               0                               0   
3                               0                               0   
4                               0                               0   

   pertumbuhan_probable_meninggal  pertumbuhan_confirmation  \
0                               0                         0   
1                               0                         0   
2                               0                         2   
3                               0                         1   
4                               0                         0   

   pertumbuhan_confirmation_selesai  pertumbuhan_confirmation_meninggal  \
0                                 0                                   0   
1                                 0                                   0   
2                                 0                                   0   
3                                 0                                   0   
4                                 0                                   0   

   Unnamed: 31  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  

[5 rows x 32 columns]

In [24]:
df_from_csv.tail()

tanggal  kode_prov            nama_prov  kode_kab        nama_kab  \
11839  2021-09-27         32  Provinsi Jawa Barat      3212  KAB. INDRAMAYU   
11840  2021-09-27         32  Provinsi Jawa Barat      3272   KOTA SUKABUMI   
11841  2021-09-27         32  Provinsi Jawa Barat      3215   KAB. KARAWANG   
11842  2021-09-27         32  Provinsi Jawa Barat      3274    KOTA CIREBON   
11843  2021-09-27         32  Provinsi Jawa Barat      3207     KAB. CIAMIS   

       closecontact  closecontact_dikarantina  closecontact_discarded  \
11839             0                         0                       0   
11840             0                         0                       0   
11841             0                         0                       0   
11842             0                         0                       0   
11843             0                         0                       0   

       suspect  suspect_diisolasi  ...  pertumbuhan_suspect_discarded  \
11839        0                  0  ...                              0   
11840        0                  0  ...                              0   
11841        0                  0  ...                              0   
11842        0                  0  ...                              0   
11843        0                  0  ...                              0   

       pertumbuhan_suspect_diisolasi  pertumbuhan_probable  \
11839                              0                     0   
11840                              0                     0   
11841                              0                     0   
11842                              0                     0   
11843                              0                     0   

       pertumbuhan_probable_discarded  pertumbuhan_probable_diisolasi  \
11839                               0                               0   
11840                               0                               0   
11841                               0                               0   
11842                               0                               0   
11843                               0                               0   

       pertumbuhan_probable_meninggal  pertumbuhan_confirmation  \
11839                               0                         0   
11840                               0                         0   
11841                               0                         0   
11842                               0                         0   
11843                               0                         0   

       pertumbuhan_confirmation_selesai  pertumbuhan_confirmation_meninggal  \
11839                                 0                                   0   
11840                                 0                                   0   
11841                                 0                                   0   
11842                                 0                                   0   
11843                                 0                                   0   

       Unnamed: 31  
11839          NaN  
11840          NaN  
11841          NaN  
11842          NaN  
11843          NaN  

[5 rows x 32 columns]

In [25]:
df_from_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11844 entries, 0 to 11843
Data columns (total 32 columns):
 #   Column                                Non-Null Count  Dtype  
---  ------                                --------------  -----  
 0   tanggal                               11844 non-null  object 
 1   kode_prov                             11844 non-null  int64  
 2   nama_prov                             11844 non-null  object 
 3   kode_kab                              11844 non-null  int64  
 4   nama_kab                              11844 non-null  object 
 5   closecontact                          11844 non-null  int64  
 6   closecontact_dikarantina              11844 non-null  int64  
 7   closecontact_discarded                11844 non-null  int64  
 8   suspect                               11844 non-null  int64  
 9   suspect_diisolasi                     11844 non-null  int64  
 10  suspect_discarded                     11844 non-null  int64  
 11  probable       

In [26]:
df_from_csv.describe()

kode_prov      kode_kab  closecontact  closecontact_dikarantina  \
count    11844.0  11844.000000       11844.0                   11844.0   
mean        32.0   3115.928571           0.0                       0.0   
std          0.0    600.468337           0.0                       0.0   
min         32.0      0.000000           0.0                       0.0   
25%         32.0   3206.750000           0.0                       0.0   
50%         32.0   3213.500000           0.0                       0.0   
75%         32.0   3272.250000           0.0                       0.0   
max         32.0   3279.000000           0.0                       0.0   

       closecontact_discarded  suspect  suspect_diisolasi  suspect_discarded  \
count                 11844.0  11844.0            11844.0            11844.0   
mean                      0.0      0.0                0.0                0.0   
std                       0.0      0.0                0.0                0.0   
min                       0.0      0.0                0.0                0.0   
25%                       0.0      0.0                0.0                0.0   
50%                       0.0      0.0                0.0                0.0   
75%                       0.0      0.0                0.0                0.0   
max                       0.0      0.0                0.0                0.0   

       probable  probable_diisolasi  ...  pertumbuhan_suspect_discarded  \
count   11844.0             11844.0  ...                        11844.0   
mean        0.0                 0.0  ...                            0.0   
std         0.0                 0.0  ...                            0.0   
min         0.0                 0.0  ...                            0.0   
25%         0.0                 0.0  ...                            0.0   
50%         0.0                 0.0  ...                            0.0   
75%         0.0                 0.0  ...                            0.0   
max         0.0                 0.0  ...                            0.0   

       pertumbuhan_suspect_diisolasi  pertumbuhan_probable  \
count                        11844.0               11844.0   
mean                             0.0                   0.0   
std                              0.0                   0.0   
min                              0.0                   0.0   
25%                              0.0                   0.0   
50%                              0.0                   0.0   
75%                              0.0                   0.0   
max                              0.0                   0.0   

       pertumbuhan_probable_discarded  pertumbuhan_probable_diisolasi  \
count                         11844.0                         11844.0   
mean                              0.0                             0.0   
std                               0.0                             0.0   
min                               0.0                             0.0   
25%                               0.0                             0.0   
50%                               0.0                             0.0   
75%                               0.0                             0.0   
max                               0.0                             0.0   

       pertumbuhan_probable_meninggal  pertumbuhan_confirmation  \
count                         11844.0              11844.000000   
mean                              0.0                 58.724755   
std                               0.0                154.543544   
min                               0.0                  0.000000   
25%                               0.0                  1.000000   
50%                               0.0                 11.000000   
75%                               0.0                 54.000000   
max                               0.0               3828.000000   

       pertumbuhan_confirmation_selesai  pertumbuhan_confirmation_meninggal  \
count                      11844.000000    